# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1inKK8Ef0HODCv3NLG786FiDpVIR-Fqn4

**K-Means Clustering of Iris dataset**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import MinMaxScaler

from google.colab import files
uploaded = files.upload()

# Load the dataset
iris = pd.read_csv('Iris.csv')
x = iris.iloc[:, [0, 1, 2, 3]].values

iris.info()
iris[0:10]

#Frequency distribution of species"
iris_outcome = pd.crosstab(index=iris["Species"],  # Make a crosstab
                              columns="count")      # Name the count column

iris_outcome

iris_setosa=iris.loc[iris["Species"]=="Iris-setosa"]
iris_virginica=iris.loc[iris["Species"]=="Iris-virginica"]
iris_versicolor=iris.loc[iris["Species"]=="Iris-versicolor"]

"""**Distribution plots**"""

sns.FacetGrid(iris,hue="Species").map(sns.distplot,"PetalLengthCm").add_legend()
sns.FacetGrid(iris,hue="Species").map(sns.distplot,"PetalWidthCm").add_legend()
sns.FacetGrid(iris,hue="Species").map(sns.distplot,"SepalWidthCm").add_legend()
sns.FacetGrid(iris,hue="Species").map(sns.distplot,"SepalLengthCm").add_legend()
plt.show()

"""**Box plot**"""

sns.boxplot(x="Species",y="PetalLengthCm",data=iris)
plt.show()

"""**Violin plot**"""

sns.violinplot(x="Species",y="PetalLengthCm",data=iris)
plt.show()

"""**Scatter plot**"""

sns.set_style("whitegrid")
sns.pairplot(iris,hue="Species");
plt.show()

"""**K Means Clustering**"""

#Finding the optimum number of clusters for k-means classification
from sklearn.cluster import KMeans
wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)

"""**Using the elbow method to determine the optimal number of clusters for k-means clustering**"""

plt.plot(range(1, 11), wcss)
plt.title('The elbow method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS') #within cluster sum of squares
plt.show()

"""**Implementing K-Means Clustering**"""

kmeans = KMeans(n_clusters = 3, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
y_kmeans = kmeans.fit_predict(x)

#Visualising the clusters
plt.scatter(x[y_kmeans == 0, 0], x[y_kmeans == 0, 1], s = 100, c = 'purple', label = 'Iris-setosa')
plt.scatter(x[y_kmeans == 1, 0], x[y_kmeans == 1, 1], s = 100, c = 'orange', label = 'Iris-versicolour')
plt.scatter(x[y_kmeans == 2, 0], x[y_kmeans == 2, 1], s = 100, c = 'green', label = 'Iris-virginica')

#Plotting the centroids of the clusters
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], s = 100, c = 'red', label = 'Centroids')

plt.legend()

"""**3d Scatterplot**"""

fig = plt.figure(figsize = (15,15))
ax = fig.add_subplot(111, projection='3d')
plt.scatter(x[y_kmeans == 0, 0], x[y_kmeans == 0, 1], s = 100, c = 'purple', label = 'Iris-setosa')
plt.scatter(x[y_kmeans == 1, 0], x[y_kmeans == 1, 1], s = 100, c = 'orange', label = 'Iris-versicolour')
plt.scatter(x[y_kmeans == 2, 0], x[y_kmeans == 2, 1], s = 100, c = 'green', label = 'Iris-virginica')

#Plotting the centroids of the clusters
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], s = 100, c = 'red', label = 'Centroids')
plt.show()